# Jinja template: Process setup.py to obtain version and metadata
{% set data = load_setup_py_data() %}

package:
  name: naps-track
  version: {{ data.get('version') }}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

build:
  number: 0
  entry_points:
    - naps-track=naps.naps_track:main

source:
  path: ../../

requirements:
  host:
    - pip
    - python=3.9

  run:
    - pip
    - python=3.9
    - sleap::sleap=1.3.0
    - pytest
    - tqdm

test:
  imports:
    - naps
    - cv2.aruco
  commands:
    - naps-track --help
