# Jinja template: Process setup.py to obtain version and metadata
{% set data = load_setup_py_data() %}

package:
  name: naps
  version: {{ data.get('version') }}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

build:
  number: 0
  entry_points:
    - naps-track=naps.naps_track:main

source:
  path: ../../

requirements:
  host:
    - pip
    - python=3.7
    - numpy>=1.19.5,<=1.21.5
    - sleap>=1.2.4
  run:
    - python=3.7
    - numpy>=1.19.5,<=1.21.5
    - scipy>=1.4.1,<=1.7.3
    - h5py>=3.1.0,<=3.6.0
    - attrs==21.2.0
    - sleap>=1.2.4
    - pandas
    - pytest
    - tqdm

outputs:
  - name: naps-track

test:
  imports:
    - naps
    - cv2.aruco
  commands:
    - naps-track --help

