version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

formats: all

conda:
  environment: docs/environment.yml

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
