version: 2

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"

# Configuration of the Sphinx documentation
sphinx:
  configuration: docs/conf.py

# This part is necessary otherwise the project is not built
python:
  version: 3.7
  install:
    - method: pip
      path: .
