version: 2

formats: all

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-22.04

sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - method: pip
      path: .
