name: naps

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - conda-forge::sleap=1.3.0
  - conda-forge::pandas
  - conda-forge::pytest
  - conda-forge::pytest-cov
  - conda-forge::tqdm
  - pip
  - pip:
      - "--editable=./"
