name: sleap
channels:
#  - sleap
#  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - conda-forge::numpy>=1.19.5,<=1.21.5
#  - conda-forge::pyside2>=5.13.2,<=5.14.1
#  - conda-forge::h5py=3.1.0
  - conda-forge::scipy>=1.4.1,<=1.7.3
#  - pillow=8.4.0
#  - shapely=1.7.1
  - conda-forge::pandas
#  - ffmpeg
#  - cudatoolkit=11.3.1
  - cudnn=8.2.1
#  - nvidia::cuda-nvcc=11.3
  - conda-forge::pip<=22.0.3
#  - sleap::sleap>=1.2.4
