name: naps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - conda-forge::numpy>=1.19.5,<=1.21.5
  - conda-forge::scipy>=1.4.1,<=1.7.3
  - conda-forge::pandas
  - conda-forge::pip<=22.0.3
  - pip:
    - sphinx-copybutton
    - sphinx-press-theme
    - myst_nb
